### ISSUE TITLE
Build is broken [build:antora ] [build:antora-perf] XXX

### ISSUE THREAD

**Issue by apupier** [apache/camel-website#823] opened 2022-04-12 15:42 UTC
It generates 208Mb of log with most of the lines having this content:

```[build:antora  ] [build:antora-perf]             XXX,```

end of the file is:

```
2022-04-12T15:31:04.5905966Z [94m➤[39m [90mYN0000[39m: [build:antora  ] ERROR: "build:antora-perf" exited with 1.
2022-04-12T15:31:04.6571212Z [94m➤[39m [90mYN0000[39m: ERROR: "build:antora" exited with 1.
2022-04-12T15:31:04.6696269Z [91m➤[39m YN0000: The command failed for workspaces that are depended upon by other workspaces; can't satisfy the dependency graph
2022-04-12T15:31:04.6698336Z [91m➤[39m YN0000: Failed with errors in 16m 25s
2022-04-12T15:31:04.7027721Z ##[error]Process completed with exit code 1.
```

see https://github.com/apache/camel-website/pull/822 and https://github.com/apache/camel-website/pull/820

**Comment by apupier** [comment] 2022-04-12 15:46
there are several ```"msg": "Could not locate 'xref:js/camel.js' in contentCatalog"```

**Comment by apupier** [comment] 2022-04-13 09:22
reproducing locally but when I search for `camel.js` or `contentCatalog` I have no result.

**Comment by apupier** [comment] 2022-04-13 09:43
related chat https://camel.zulipchat.com/#narrow/stream/257618-camel-website/topic/Could.20not.20locate.20xref.3Ajs.2Fcamel.2Ejs

(containing explanation for the issue)

**Comment by zregvart** [comment] 2022-04-13 10:44
Duplicate of https://issues.apache.org/jira/browse/CAMEL-17961

**Closed by zregvart** 2022-04-13 10:44 UTC
