### ISSUE TITLE
XML code blocks are hardly readable with tags in dark blue on black background

### ISSUE THREAD

**Issue by apupier** [apache/camel-website#861] opened 2022-06-22 08:30 UTC
![Screenshot from 2022-06-22 10-29-26](https://user-images.githubusercontent.com/1105127/174982229-2b7658ec-23aa-4b04-a030-ec4afb22d85e.png)

**Comment by zregvart** [comment] 2022-06-22 08:50
Most likely duplicate of #862

**Closed** 2022-08-09 08:48 UTC
